"""Indexer module: parse .repos files and generate lockfiles.

The indexer is responsible for:
- Parsing .repos YAML files (VCS format)
- Resolving versions (tags/branches/SHAs) to concrete SHAs via blobless clone
- Fetching package.xml files from git objects (no working tree needed)
- Generating dual-indexed lockfiles (repos + packages)
"""

from __future__ import annotations

import io
import logging
import os
import subprocess
import tarfile
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

import yaml

from roscope.exceptions import GitError, RoscopeError, XmlParseError
from roscope.types import (
    Dependencies,
    DependencyGraph,
    DependencyMode,
    Lockfile,
    PackageInfo,
    PackageLock,
    RepoEntry,
    RepoLock,
    ReposFile,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# YAML parsing / serialization
# ---------------------------------------------------------------------------

LOCKFILE_HEADER = """\
# roscope lockfile (VCS-compatible)
#
# This file is auto-generated by `roscope index`. Do not edit manually.
# To regenerate, run: roscope index <your.repos>
#
# VCS import: vcs import src < manifest.lock.repos
#
# This lockfile pins exact commit SHAs for all repositories in your .repos file,
# ensuring reproducible builds. It contains:
#   - repositories: Repository metadata with pinned SHAs (VCS-compatible)
#   - packages: Package index for O(1) dependency lookup
#
"""


def parse_repos(content: str) -> ReposFile:
    """Parse a .repos file from YAML content."""
    raw = yaml.safe_load(content)
    if not isinstance(raw, dict) or "repositories" not in raw:
        raise RoscopeError("invalid .repos file: missing 'repositories' key")

    repos: dict[str, RepoEntry] = {}
    for path, entry in raw["repositories"].items():
        repos[path] = RepoEntry(
            repo_type=entry.get("type", "git"),
            url=entry["url"],
            version=entry["version"],
        )
    return ReposFile(repositories=repos)


def parse_lockfile(content: str) -> Lockfile:
    """Parse a lockfile from YAML content."""
    raw = yaml.safe_load(content)
    if not isinstance(raw, dict):
        raise RoscopeError("invalid lockfile: not a YAML mapping")

    lockfile = Lockfile()

    for ws_path, repo_raw in (raw.get("repositories") or {}).items():
        lockfile.repositories[ws_path] = RepoLock(
            url=repo_raw["url"],
            version=repo_raw["version"],
            repo_type=repo_raw.get("type", "git"),
            version_ref=repo_raw.get("ref"),
            packages=list(repo_raw.get("packages", [])),
        )

    for pkg_name, pkg_raw in (raw.get("packages") or {}).items():
        lockfile.packages[pkg_name] = PackageLock(
            repo=pkg_raw["repo"],
            path=pkg_raw["path"],
        )

    return lockfile


def serialize_lockfile(lockfile: Lockfile) -> str:
    """Serialize a lockfile to YAML with header comment."""
    # Build ordered dict for deterministic output
    repos_out: dict[str, dict] = {}
    for ws_path in sorted(lockfile.repositories):
        repo = lockfile.repositories[ws_path]
        entry: dict = {
            "type": repo.repo_type,
            "url": repo.url,
            "version": repo.version,
        }
        if repo.version_ref is not None:
            entry["ref"] = repo.version_ref
        entry["packages"] = sorted(repo.packages)
        repos_out[ws_path] = entry

    pkgs_out: dict[str, dict] = {}
    for pkg_name in sorted(lockfile.packages):
        pkg = lockfile.packages[pkg_name]
        pkgs_out[pkg_name] = {"repo": pkg.repo, "path": pkg.path}

    data = {"repositories": repos_out, "packages": pkgs_out}
    body: str = yaml.dump(data, default_flow_style=False, sort_keys=False)
    return LOCKFILE_HEADER + body


# ---------------------------------------------------------------------------
# REP-149 condition expression evaluator
# ---------------------------------------------------------------------------


def evaluate_condition(condition: str) -> bool:
    """Evaluate a REP-149 condition expression against the current environment.

    Returns True if the condition evaluates to true (or is empty).

    Implements the full REP-149 condition grammar:
    - Comparison operators: ==, !=, <, <=, >, >= (string comparison)
    - Logical operators: and, or (left-associative, ``and`` binds tighter)
    - Parentheses for grouping
    - Terms: $VAR (env variable), bare words (alphanums/_/-), quoted strings
    """
    return _evaluate_condition_impl(condition, os.environ.get)


def _evaluate_condition_impl(
    condition: str,
    env_lookup: object,
) -> bool:
    """Evaluate with an injectable env lookup (for testing)."""
    tokens = _tokenize_condition(condition)
    if not tokens:
        return True
    parser = _ConditionParser(tokens, env_lookup)  # type: ignore[arg-type]
    result = parser.parse_expr()
    if parser.pos != len(parser.tokens):
        raise ValueError(f"unexpected token at position {parser.pos}: {parser.tokens[parser.pos]}")
    return result


def _tokenize_condition(s: str) -> list[tuple[str, str]]:
    """Tokenize a condition string into (type, value) tuples."""
    tokens: list[tuple[str, str]] = []
    chars = list(s)
    i = 0
    n = len(chars)

    while i < n:
        c = chars[i]

        if c.isspace():
            i += 1
            continue

        if c == "(":
            tokens.append(("LPAREN", "("))
            i += 1
            continue

        if c == ")":
            tokens.append(("RPAREN", ")"))
            i += 1
            continue

        # Two-char comparison operators
        if i + 1 < n:
            two = chars[i] + chars[i + 1]
            if two in ("==", "!=", "<=", ">="):
                tokens.append(("CMP", two))
                i += 2
                continue

        if c == "<":
            tokens.append(("CMP", "<"))
            i += 1
            continue
        if c == ">":
            tokens.append(("CMP", ">"))
            i += 1
            continue

        # Variable: $[A-Za-z0-9_]+
        if c == "$":
            start = i + 1
            i += 1
            while i < n and (chars[i].isalnum() or chars[i] == "_"):
                i += 1
            if i == start:
                raise ValueError("empty variable name after '$'")
            tokens.append(("VAR", "".join(chars[start:i])))
            continue

        # Quoted string
        if c in ('"', "'"):
            quote = c
            i += 1
            start = i
            while i < n and chars[i] != quote:
                i += 1
            if i >= n:
                raise ValueError(f"unterminated {quote}-quoted string")
            tokens.append(("LIT", "".join(chars[start:i])))
            i += 1  # skip closing quote
            continue

        # Bare word: alphanums, underscore, dash
        if c.isalnum() or c in ("_", "-"):
            start = i
            while i < n and (chars[i].isalnum() or chars[i] in ("_", "-")):
                i += 1
            word = "".join(chars[start:i])
            if word == "and":
                tokens.append(("AND", "and"))
            elif word == "or":
                tokens.append(("OR", "or"))
            else:
                tokens.append(("LIT", word))
            continue

        raise ValueError(f"unexpected character '{c}'")

    return tokens


class _ConditionParser:
    """Recursive-descent parser/evaluator for REP-149 conditions."""

    def __init__(
        self,
        tokens: list[tuple[str, str]],
        env_lookup: object,
    ) -> None:
        self.tokens = tokens
        self.pos = 0
        self._env_lookup = env_lookup

    def _resolve(self, tok: tuple[str, str]) -> str:
        kind, val = tok
        if kind == "VAR":
            result = self._env_lookup(val)  # type: ignore[operator]
            return result if result is not None else ""
        if kind == "LIT":
            return val
        raise ValueError(f"expected term, got {tok}")

    def _peek(self) -> tuple[str, str] | None:
        return self.tokens[self.pos] if self.pos < len(self.tokens) else None

    def _next(self) -> tuple[str, str] | None:
        if self.pos < len(self.tokens):
            tok = self.tokens[self.pos]
            self.pos += 1
            return tok
        return None

    def parse_expr(self) -> bool:
        return self._parse_or()

    def _parse_or(self) -> bool:
        result = self._parse_and()
        while self._peek() == ("OR", "or"):
            self._next()
            rhs = self._parse_and()
            result = result or rhs
        return result

    def _parse_and(self) -> bool:
        result = self._parse_atom()
        while self._peek() == ("AND", "and"):
            self._next()
            rhs = self._parse_atom()
            result = result and rhs
        return result

    def _parse_atom(self) -> bool:
        if self._peek() == ("LPAREN", "("):
            self._next()
            result = self.parse_expr()
            if self._next() != ("RPAREN", ")"):
                raise ValueError("expected ')'")
            return result
        return self._parse_comparison()

    def _parse_comparison(self) -> bool:
        lhs_tok = self._next()
        if lhs_tok is None:
            raise ValueError("expected term")
        lhs = self._resolve(lhs_tok)

        op_tok = self._next()
        if op_tok is None or op_tok[0] != "CMP":
            raise ValueError(f"expected comparison operator, got {op_tok}")
        op = op_tok[1]

        rhs_tok = self._next()
        if rhs_tok is None:
            raise ValueError("expected term after operator")
        rhs = self._resolve(rhs_tok)

        if op == "==":
            return lhs == rhs
        if op == "!=":
            return lhs != rhs
        if op == "<":
            return lhs < rhs
        if op == "<=":
            return lhs <= rhs
        if op == ">":
            return lhs > rhs
        if op == ">=":
            return lhs >= rhs
        raise ValueError(f"unknown operator: {op}")


# ---------------------------------------------------------------------------
# package.xml parsing
# ---------------------------------------------------------------------------

_DEP_TAG_MAP = {
    "build_depend": "build",
    "build_export_depend": "build_export",
    "buildtool_depend": "buildtool",
    "buildtool_export_depend": "buildtool_export",
    "exec_depend": "exec",
    "test_depend": "test",
}


def parse_package_xml(content: str, path: str) -> PackageInfo:
    """Parse package.xml content to extract package information."""
    try:
        root = ET.fromstring(content)  # noqa: S314
    except ET.ParseError as e:
        raise XmlParseError(f"failed to parse package.xml at {path}: {e}") from e

    name_el = root.find("name")
    if name_el is None or not (name_el.text or "").strip():
        raise XmlParseError("package.xml missing <name> element")

    name = (name_el.text or "").strip()
    deps = Dependencies()

    for tag, attr in _DEP_TAG_MAP.items():
        dep_list: list[str] = getattr(deps, attr)
        for el in root.findall(tag):
            cond = el.get("condition")
            if cond is not None:
                try:
                    if not evaluate_condition(cond):
                        continue
                except ValueError:
                    logger.warning("failed to evaluate condition '%s'; including dependency", cond)
            dep_text = (el.text or "").strip()
            if dep_text and dep_text not in dep_list:
                dep_list.append(dep_text)

    # <depend> expands to build + build_export + exec (REP-149 §3)
    for el in root.findall("depend"):
        cond = el.get("condition")
        if cond is not None:
            try:
                if not evaluate_condition(cond):
                    continue
            except ValueError:
                logger.warning("failed to evaluate condition '%s'; including dependency", cond)
        dep_text = (el.text or "").strip()
        if dep_text:
            if dep_text not in deps.build:
                deps.build.append(dep_text)
            if dep_text not in deps.build_export:
                deps.build_export.append(dep_text)
            if dep_text not in deps.exec:
                deps.exec.append(dep_text)

    # Sort all lists for deterministic output
    deps.build.sort()
    deps.build_export.sort()
    deps.buildtool.sort()
    deps.buildtool_export.sort()
    deps.exec.sort()
    deps.test.sort()

    return PackageInfo(name=name, path=path, dependencies=deps)


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------


def _run_git(
    args: list[str],
    *,
    cwd: Path | str | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    """Run a git command and return the result."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as e:
        raise GitError(f"failed to run git {args[0]}: {e}") from e

    if check and result.returncode != 0:
        raise GitError(f"git {' '.join(args)} failed: {result.stderr.strip()}")

    return result


def _run_git_bytes(
    args: list[str],
    *,
    cwd: Path | str | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[bytes]:
    """Run a git command returning raw bytes (for binary output like ``git archive``)."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            check=False,
        )
    except OSError as e:
        raise GitError(f"failed to run git {args[0]}: {e}") from e

    if check and result.returncode != 0:
        raise GitError(
            f"git {' '.join(args)} failed: {result.stderr.decode(errors='replace').strip()}"
        )

    return result


def resolve_version_local(repo_dir: Path, url: str, version_ref: str) -> str:
    """Resolve a ref to a SHA using a local clone via ``git fetch``.

    Preferred over ls-remote when a local clone exists.
    """
    _run_git(["fetch", "--", url, version_ref], cwd=repo_dir)
    result = _run_git(["rev-parse", "FETCH_HEAD"], cwd=repo_dir)
    sha = result.stdout.strip()
    logger.debug("Resolved %s to SHA %s via local fetch", version_ref, sha)
    return sha


def blobless_clone(url: str, repo_dir: Path) -> None:
    """Blobless no-checkout clone of a repository."""
    if repo_dir.parent and not repo_dir.parent.exists():
        repo_dir.parent.mkdir(parents=True, exist_ok=True)
    logger.debug("Blobless clone %s into %s", url, repo_dir)
    _run_git(["clone", "--filter=blob:none", "--no-checkout", url, str(repo_dir)])


def ensure_remote_url(repo_dir: Path, expected_url: str) -> None:
    """Ensure origin URL matches for partial clones.

    Blobless/partial clones use origin as the promisor remote. If the manifest
    URL changed, origin must be updated.
    """
    # Only act on partial clones
    result = _run_git(
        ["config", "--get", "remote.origin.partialclonefilter"],
        cwd=repo_dir,
        check=False,
    )
    if result.returncode != 0:
        return  # Not a partial clone

    result = _run_git(["remote", "get-url", "origin"], cwd=repo_dir, check=False)
    if result.returncode != 0:
        return  # No origin remote
    current_url = result.stdout.strip()

    if current_url == expected_url:
        return

    logger.debug("Updating origin URL for %s to %s", repo_dir, expected_url)
    _run_git(["remote", "set-url", "origin", expected_url], cwd=repo_dir)


# ---------------------------------------------------------------------------
# Package discovery
# ---------------------------------------------------------------------------


def discover_packages(
    url: str,
    sha: str,
    repo_dir: Path | None = None,
    recurse_submodules: bool = False,
) -> list[PackageInfo]:
    """Discover all packages in a repository and parse their package.xml files.

    Three strategies are tried in order:
    1. Existing local repo: inspect objects via ``git ls-tree`` + ``git show``
    2. ``git archive --remote``: fetch tree as tar stream
    3. Blobless clone into repo_dir, then strategy 1
    """
    # Strategy 1: existing local repo
    if repo_dir is not None and repo_dir.exists() and (repo_dir / ".git").exists():
        logger.debug("Using existing repo at %s", repo_dir)
        return _discover_from_existing_repo(repo_dir, url, sha, recurse_submodules)

    # Strategy 2: git archive (skip if submodules needed)
    if not recurse_submodules:
        result = _run_git_bytes(["archive", "--remote", url, sha], check=False)
        if result.returncode == 0:
            return _discover_from_tar(result.stdout)

    # Strategy 3: blobless clone
    if repo_dir is None:
        raise GitError("a source directory (--src) is required to clone repositories")

    blobless_clone(url, repo_dir)
    return _discover_from_existing_repo(repo_dir, url, sha, recurse_submodules)


def _discover_from_tar(tar_data: bytes) -> list[PackageInfo]:
    """Discover packages from a tar archive (git archive output)."""
    packages: list[PackageInfo] = []
    with tarfile.open(fileobj=io.BytesIO(tar_data)) as archive:
        for member in archive.getmembers():
            path_str = member.name
            if not (path_str.endswith("/package.xml") or path_str == "package.xml"):
                continue
            f = archive.extractfile(member)
            if f is None:
                continue
            content = f.read().decode("utf-8", errors="replace")
            parent = str(Path(path_str).parent)
            pkg_path = parent if parent != "." else "."

            try:
                info = parse_package_xml(content, pkg_path)
                logger.debug("Found package '%s' at %s", info.name, pkg_path)
                packages.append(info)
            except RoscopeError as e:
                logger.warning("Failed to parse %s: %s", path_str, e)

    logger.debug("Found %d packages from archive", len(packages))
    return packages


def _discover_from_existing_repo(
    repo_dir: Path,
    url: str,
    sha: str,
    recurse_submodules: bool,
) -> list[PackageInfo]:
    """Discover packages from an existing git repository using git object inspection."""
    # Fetch the SHA directly from the URL
    logger.debug("Fetching %s from %s in existing repo...", sha, url)
    result = _run_git(["fetch", "--depth=1", "--", url, sha], cwd=repo_dir, check=False)
    if result.returncode != 0:
        logger.debug("Specific SHA fetch failed, trying general fetch...")
        _run_git(["fetch", "--depth=1", "--", url], cwd=repo_dir, check=False)

    packages = _discover_from_git_objects(repo_dir, sha)

    if recurse_submodules:
        sub_packages = _discover_from_submodules(repo_dir, sha)
        packages.extend(sub_packages)

    logger.debug("Found %d packages via git object inspection", len(packages))
    return packages


def _discover_from_git_objects(repo_dir: Path, sha: str) -> list[PackageInfo]:
    """Discover packages by reading git objects directly (no checkout needed)."""
    result = _run_git(["ls-tree", "-r", "--name-only", sha], cwd=repo_dir)
    packages: list[PackageInfo] = []

    for line in result.stdout.splitlines():
        if not (line.endswith("/package.xml") or line == "package.xml"):
            continue

        file_ref = f"{sha}:{line}"
        content_result = _run_git(["show", file_ref], cwd=repo_dir, check=False)
        if content_result.returncode != 0:
            continue

        parent = str(Path(line).parent)
        pkg_path = parent if parent != "." else "."

        try:
            info = parse_package_xml(content_result.stdout, pkg_path)
            logger.debug("Found package '%s' at %s", info.name, pkg_path)
            packages.append(info)
        except RoscopeError as e:
            logger.warning("Failed to parse %s: %s", line, e)

    return packages


def _discover_from_submodules(repo_dir: Path, sha: str) -> list[PackageInfo]:
    """Discover packages from submodules using git object inspection."""
    gitmodules_ref = f"{sha}:.gitmodules"
    result = _run_git(["show", gitmodules_ref], cwd=repo_dir, check=False)
    if result.returncode != 0:
        return []

    packages: list[PackageInfo] = []
    current_path: str | None = None

    for line in result.stdout.splitlines():
        trimmed = line.strip()
        if trimmed.startswith("path = "):
            current_path = trimmed[len("path = ") :]
        elif trimmed.startswith("[submodule"):
            current_path = None

        if current_path is None:
            continue

        path = current_path
        # Get submodule commit SHA from the tree
        ls_result = _run_git(["ls-tree", sha, path], cwd=repo_dir, check=False)
        if ls_result.returncode != 0:
            current_path = None
            continue

        first_line = ls_result.stdout.splitlines()[0] if ls_result.stdout.strip() else ""
        parts = first_line.split()
        if len(parts) >= 3 and parts[1] == "commit":
            submodule_sha = parts[2]
            submodule_dir = repo_dir / path

            if (submodule_dir / ".git").exists():
                logger.debug(
                    "Inspecting submodule at %s (SHA: %s)",
                    path,
                    submodule_sha[:8],
                )
                _run_git(
                    ["fetch", "--depth=1", "origin", submodule_sha],
                    cwd=submodule_dir,
                    check=False,
                )
                try:
                    sub_packages = _discover_from_git_objects(submodule_dir, submodule_sha)
                    for pkg in sub_packages:
                        pkg.path = f"{path}/{pkg.path}"
                    packages.extend(sub_packages)
                except RoscopeError:
                    pass

        current_path = None

    return packages


# ---------------------------------------------------------------------------
# Version resolution
# ---------------------------------------------------------------------------


def _resolve_version_from_repo(
    url: str,
    version: str,
    repo_dir: Path | None,
) -> str:
    """Resolve a version (tag, branch, or SHA) to a concrete SHA."""
    # Short-circuit: full SHAs are already resolved
    if len(version) == 40 and all(c in "0123456789abcdefABCDEF" for c in version):
        logger.debug("Version %s is a full SHA, using directly", version)
        return version

    if repo_dir is None:
        raise GitError(
            f"a source directory (--src) is required to resolve non-SHA version '{version}'"
        )

    # Ensure a local clone exists
    if not (repo_dir / ".git").exists():
        blobless_clone(url, repo_dir)
    else:
        ensure_remote_url(repo_dir, url)

    return resolve_version_local(repo_dir, url, version)


# ---------------------------------------------------------------------------
# Lockfile generation
# ---------------------------------------------------------------------------


def generate_lockfile(
    repos: ReposFile,
    src_dir: Path | None = None,
    recurse_submodules: bool = False,
) -> Lockfile:
    """Generate a lockfile from a .repos file.

    Resolves versions to SHAs and discovers packages in each repository.
    """
    lockfile = Lockfile()

    for workspace_path, entry in repos.repositories.items():
        if entry.repo_type != "git":
            logger.warning(
                "Skipping non-git repository at %s: type=%s",
                workspace_path,
                entry.repo_type,
            )
            continue

        repo_dir = src_dir / workspace_path if src_dir is not None else None

        # Resolve version to SHA
        sha = _resolve_version_from_repo(entry.url, entry.version, repo_dir)
        logger.debug("Resolved %s %s -> %s", workspace_path, entry.version, sha)

        # Discover packages
        packages = discover_packages(entry.url, sha, repo_dir, recurse_submodules)

        package_names = sorted(p.name for p in packages)

        # Only include ref if different from resolved SHA
        version_ref = entry.version if entry.version != sha else None

        lockfile.repositories[workspace_path] = RepoLock(
            url=entry.url,
            version=sha,
            repo_type="git",
            version_ref=version_ref,
            packages=package_names,
        )

        for pkg in packages:
            if pkg.name in lockfile.packages:
                existing = lockfile.packages[pkg.name]
                raise RoscopeError(
                    f"duplicate package '{pkg.name}' found in repos "
                    f"'{existing.repo}' and '{workspace_path}'"
                )
            lockfile.packages[pkg.name] = PackageLock(
                repo=workspace_path,
                path=pkg.path,
            )

    return lockfile


# ---------------------------------------------------------------------------
# Source directory scanning (dirty mode)
# ---------------------------------------------------------------------------


def scan_source_dir(src_dir: Path) -> Lockfile:
    """Build a synthetic Lockfile by scanning a source directory for packages.

    Walks ``src_dir`` recursively, finds every ``package.xml``, and maps each
    package to a ``PackageLock``.  The resulting ``Lockfile`` has empty
    ``url`` / ``version`` fields (sufficient for dirty-mode resolution, where
    git operations are never performed).

    Intended for ``--dirty`` mode: lets users work without a lockfile after
    a plain ``vcs import src < some.repos``.  Works equally well when there is
    no remote, or when the directory is not a git repository at all.

    Traversal rules:
    - Recurse into every subdirectory except ``.git/``.
    - When ``package.xml`` is found at a node, record the package and stop
      recursing into that directory (ROS packages don't nest inside each other).
    - Duplicate package names: warn and keep the first occurrence.
    """
    lockfile = Lockfile()
    seen: dict[str, Path] = {}  # pkg_name -> first absolute path
    src_dir = src_dir.resolve()

    def _walk(directory: Path) -> None:
        try:
            entries = sorted(directory.iterdir())
        except OSError:
            return
        for entry in entries:
            if not entry.is_dir() or entry.name == ".git":
                continue
            xml = entry / "package.xml"
            if xml.exists():
                try:
                    info = parse_package_xml(xml.read_text(), str(xml))
                except RoscopeError as e:
                    logger.warning("scan_source_dir: skipping %s: %s", xml, e)
                    continue

                if info.name in seen:
                    logger.warning(
                        "scan_source_dir: duplicate package '%s' at %s and %s; keeping first",
                        info.name,
                        seen[info.name],
                        entry,
                    )
                    continue

                seen[info.name] = entry

                # repo  = immediate child of src_dir that contains this package
                # path  = relative path from that child to the package dir
                # fetch_dir / repo / path  must equal entry.resolve()
                try:
                    rel = entry.relative_to(src_dir)
                except ValueError:
                    logger.warning("scan_source_dir: %s outside src_dir; skipping", entry)
                    continue
                repo_key = rel.parts[0]  # immediate child of src_dir
                path_in_repo = str(Path(*rel.parts[1:])) if len(rel.parts) > 1 else "."

                if repo_key not in lockfile.repositories:
                    lockfile.repositories[repo_key] = RepoLock(url="", version="")

                lockfile.packages[info.name] = PackageLock(
                    repo=repo_key,
                    path=path_in_repo,
                )
                # Do not recurse: ROS packages don't contain other packages
            else:
                _walk(entry)

    _walk(src_dir)
    logger.info(
        "scan_source_dir: found %d packages in %d repos under %s",
        len(lockfile.packages),
        len(lockfile.repositories),
        src_dir,
    )
    return lockfile


# ---------------------------------------------------------------------------
# Dependency resolution
# ---------------------------------------------------------------------------


def _read_package_deps(
    lockfile: Lockfile,
    src_dir: Path,
    pkg_name: str,
) -> Dependencies | None:
    """Read on-disk package.xml dependencies for a package."""
    pkg_lock = lockfile.packages.get(pkg_name)
    if pkg_lock is None:
        return None
    xml_path = src_dir / pkg_lock.repo / pkg_lock.path / "package.xml"
    try:
        content = xml_path.read_text()
    except OSError:
        return None
    try:
        info = parse_package_xml(content, str(xml_path))
        return info.dependencies
    except RoscopeError:
        return None


def resolve_dependencies(
    lockfile: Lockfile,
    src_dir: Path,
    root_packages: set[str],
    mode: DependencyMode,
) -> DependencyGraph:
    """Compute transitive dependencies for a set of root packages.

    Reads dependency information from on-disk ``package.xml`` files.
    Packages not on disk are treated as leaves.
    """
    result = DependencyGraph()
    queue = list(root_packages)
    visited: set[str] = set()

    while queue:
        pkg_name = queue.pop()
        if pkg_name in visited:
            continue
        visited.add(pkg_name)

        if pkg_name not in lockfile.packages:
            result.external.add(pkg_name)
            continue

        result.packages.add(pkg_name)

        deps = _read_package_deps(lockfile, src_dir, pkg_name)
        if deps is None:
            result.missing.add(pkg_name)
            continue

        if mode == DependencyMode.BUILD:
            queue.extend(deps.build)
            queue.extend(deps.build_export)
            queue.extend(deps.buildtool)
            queue.extend(deps.buildtool_export)
        elif mode == DependencyMode.EXEC:
            queue.extend(deps.exec)
        elif mode == DependencyMode.BUILD_AND_EXEC:
            queue.extend(deps.build)
            queue.extend(deps.build_export)
            queue.extend(deps.buildtool)
            queue.extend(deps.buildtool_export)
            queue.extend(deps.exec)
        elif mode == DependencyMode.ALL:
            queue.extend(deps.build)
            queue.extend(deps.build_export)
            queue.extend(deps.buildtool)
            queue.extend(deps.buildtool_export)
            queue.extend(deps.exec)
            queue.extend(deps.test)

    return result


def compute_build_order(
    lockfile: Lockfile,
    src_dir: Path,
    packages: set[str],
) -> list[str]:
    """Compute build order for packages using topological sort (Kahn's algorithm).

    Returns packages in dependency order (dependencies first).
    """
    in_degree: dict[str, int] = dict.fromkeys(packages, 0)
    dependents: dict[str, list[str]] = defaultdict(list)

    for pkg in packages:
        deps = _read_package_deps(lockfile, src_dir, pkg)
        if deps is None:
            continue
        build_deps = deps.build + deps.build_export + deps.buildtool + deps.buildtool_export
        for dep in build_deps:
            if dep in packages:
                in_degree[pkg] += 1
                dependents[dep].append(pkg)

    # Kahn's algorithm
    result: list[str] = []
    queue = sorted(pkg for pkg, deg in in_degree.items() if deg == 0)

    while queue:
        pkg = queue.pop()
        result.append(pkg)

        for dep in dependents.get(pkg, []):
            in_degree[dep] -= 1
            if in_degree[dep] == 0:
                queue.append(dep)
                queue.sort()

    # Add any remaining packages (cycles) at the end
    for pkg in sorted(packages):
        if pkg not in result:
            result.append(pkg)

    return result
